### ISSUE TITLE
アクティベーションについて

### ISSUE THREAD

**Issue by catfist** [Band-Aid/Go-Qiita#8]
毎回qiita-launchするのが面倒なので、とりあえず`activationEvents`を`"onLanguage:markdown"`にして使っているのですが、
どのみちアクセストークンをファイルに書き込む必要があるのであれば、記事ディレクトリに.vscode\qiita.jsonでも作って、そこにアクセストークンをストア、アクティベーションは`workspaceContains`にしてはどうでしょうか？
その方が管理もしやすいですし、セキュリティ的には変わりませんし。

**Comment by Band-Aid** [comment]
ご意見ありがとうございます。
はい、これは自分もずっと直さないといけないなと思っていた部分ですなのですが、vscodeの勉強がてらhello worldサンプルから作ったので深くかんがえていませんでした。
activationEventsを"onLanguage:markdown"いいですね。検討してみます。

workspaceContainsから起動する方法も調べてみます。

**Comment by Band-Aid** [comment]
`onLanguage:markdown`対応しました。
`workspaceContains`も検討しましたが、記事ディレクトリが同じとは限らないのでやめました。
